name: Install node js

description: common action for install node js

runs:
  using: composite
  steps:
    - name: Use node js
      uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Install dependecies
      run: make install
      shell: bash